---
# compose 3.7 / docker version needed -> 18.06.0+

version: '3.7'

services:
  ssh_server01:
    hostname: ubuntu22_server01
    container_name: ubuntu22_server01
    build:
      context: ./files_ubuntu22_server01
    cap_add: 
      - NET_ADMIN
    ports: 
      - "2221:22"
    command: ["/usr/bin/docker-entrypoint.sh"] 

  ssh_server02:
    hostname: centos8_server02
    container_name: centos8_server02
    build:
      context: ./files_centos8_server02
    cap_add: 
      - NET_ADMIN
    ports: 
      - "2223:22"


  ssh_server03:
    hostname: windowsltsc2019_server03
    container_name: windowsltsc2019_server03
    build:
      context: ./files_windowsltsc2019_server03

  # ssh_server04:
  #   image: mcr.microsoft.com/windows/servercore:ltsc2019
  #   container_name: windowservice
  #   restart: always
  #   mem_limit: 10g
  #   # volumnes:
  #   #   - /sourcepath:/dockerpath
  #   ports: 
  #     - "2224:22"        